WebLevio/Areas/adminstrator/Controllers/MandatController.cs
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Mvc;
using Data;
 
namespace WebLevio.Areas.adminstrator.Controllers
{
    public class MandatController : Controller
    {

        private Contexte2 ctx = new Contexte2();

        private String url = "http://localhost:18080/LevioMap-web/api/mandats/";
        // GET: adminstrator/Mandat
       

    //consommation web service

        [HttpGet]
        public ActionResult ListeMandat()
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri(url);
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = client.GetAsync("listeMandat").Result;
            if (response.IsSuccessStatusCode)
            {
                ViewBag.result = response.Content.ReadAsAsync<IEnumerable<mandat>>().Result;
            }
            else
            {
                ViewBag.result = "Error";
            }

            return View();
        }


        [HttpGet]
        public ActionResult AddMandat()
        {
            return View();
        }
        [HttpPost]
        public ActionResult EditAction(FormCollection collection)
        {
            try

            {

                var client = new RestClient(url);

                var request = new RestRequest("edit", Method.PUT);


                request.AddHeader("Content-type", "application/json");
                request.AddJsonBody(
                    new
                    {
                        idMandat = collection["idMandat"],
                        dateDebut = collection["dateDebut"],
                        dateFin = collection["dateFin"]
                    }); // 
                        // execute the request
                IRestResponse response = client.Execute(request);
                var content = response.Content;
            
                    return RedirectToAction("ListeMandat");
               


            }

            catch

            {
 
                return View();
            }
        }
        [HttpPost]
        public ActionResult AddMandat(FormCollection collection)
        {

            try

            {

                var client = new RestClient(url);

                var request = new RestRequest("assign", Method.POST);
                request.AddParameter("projetId", collection["projet_idProjet"], ParameterType.QueryString);
                request.AddParameter("resourceId", collection["ressource_idRessource"], ParameterType.QueryString);
                request.AddParameter("dateDebut", collection["dateDebut"], ParameterType.QueryString);
                request.AddParameter("dateFin", collection["dateFin"], ParameterType.QueryString);
                request.AddHeader("Accept", "application/json");
                // execute the request
                IRestResponse response = client.Execute(request);
                var content = response.Content;
                Console.WriteLine(request.ToString());
                Console.WriteLine(response.Content);
                return RedirectToAction("ListeMandat");
            }

            catch

            {
                return View();
            }
        }




        [HttpPost]
        public ActionResult DeleteMandat()
        {

            try

            {
                var routeValues = Url.RequestContext.RouteData.Values;
                var paramName = "mandateid";
                var id = routeValues.ContainsKey(paramName) ?
                    routeValues[paramName] :
                    Request.QueryString[paramName];
                Console.WriteLine(id.ToString());
                var client = new RestClient(url);

                var request = new RestRequest("delete", Method.POST);
                request.AddParameter("mandateid", id, ParameterType.QueryString);

                request.AddHeader("Accept", "application/json");
                Console.WriteLine(request.ToString());
                // execute the request
                IRestResponse response = client.Execute(request);
                var content = response.Content;

                Console.WriteLine(response.Content);
                return RedirectToAction("Index");
            }

            catch

            {
                return View();
            }
        }






       
        public ActionResult EditMandate(FormCollection collection,int id)
        {
            try

            {
                
                    var client = new RestClient(url);

                    var request = new RestRequest("mandats/edit", Method.PUT);


                    request.AddHeader("Content-type", "application/json");
                    request.AddJsonBody(
                        new
                        {
                            idMandat = collection["idMandat"],
                            dateDebut = collection["dateDebut"],
                            dateFin = collection["dateFin"]
                        }); // 
                            // execute the request
                    IRestResponse response = client.Execute(request);
                    var content = response.Content;
                mandat m = ctx.mandat.Where(x => x.idMandat.Equals(id)).First();

                if ( response.StatusCode.Equals("200"))
                    return RedirectToAction("ListeMandat");
           else
                    return View(m);
                

            }

            catch

            {
            
                mandat m = ctx.mandat.Where(x => x.idMandat.Equals(id)).First();
                return View(m);
            }
        }




        //methodes .Net


        public ActionResult Historique()
        {
            List<mandat> mandat = ctx.mandat.Where(x => x.dateFin < DateTime.Today).ToList();
            ViewBag.res = mandat;
            return View(mandat);
        }


        public ActionResult Archive()
        {
            List<mandat> mandat = ctx.mandat.Where(x => x.archive == true).ToList();


            ViewBag.res = mandat;
            return View(mandat);
        }



        public ActionResult getMandatsNotif()
        {

            List<mandat> ms = new List<Data.mandat>(); 
            //   List<mandat> mandat = ctx.mandat.Where (x=> System.Data.Entity.DbFunctions.DiffDays(x.dateFin,DateTime.Now)>=10).ToList();
            List<mandat> mandat = ctx.mandat.Where(x =>x.dateFin>DateTime.Now).ToList();
            foreach(var o in mandat)
            {
                if(calday(o.dateFin,DateTime.Now)<40)
                {
                    ms.Add(o);
                }
            }
            ViewBag.noti = ms.Count;
            ViewBag.res = ms;
            return View(ms);
        }

        public int nbrMandate()
        {

            List<mandat> ms = new List<Data.mandat>();
            //   List<mandat> mandat = ctx.mandat.Where (x=> System.Data.Entity.DbFunctions.DiffDays(x.dateFin,DateTime.Now)>=10).ToList();
            List<mandat> mandat = ctx.mandat.Where(x => x.dateFin > DateTime.Now).ToList();
            foreach (var o in mandat)
            {
                if (calday(o.dateFin, DateTime.Now) < 40)
                {
                    ms.Add(o);
                }
            }
            return ms.Count;
        }




        public double calday(DateTime d1,DateTime d2)
        {
            

            return (d1 - d2).TotalDays ;
        }

      
        
        
         
        public PartialViewResult Header()
        {
            int m = nbrMandate();
            ViewBag.n = m;
         return PartialView();
        }


    }
}

WebLevio/Areas/adminstrator/Views/Shared/_adminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*@Styles.Render("~/Content/admin/css")*@
    <link id="bootstrap-style" href= @Url.Content("../..//Content/bootstrap.css") rel="stylesheet">
    <link href=@Url.Content("../..//Content/bootstrap-responsive.min.css") rel="stylesheet">
    <link id="base-style" href=@Url.Content("../..//Content/style.css") rel="stylesheet">
    <link id="base-style-responsive" href=@Url.Content("../..//Content/style-responsive.css") rel="stylesheet">
    <!-- end: CSS -->
    <script src=@Url.Content("/js/jquery-1.9.1.min.js")></script>

    <!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <!-- start: Favicon -->
    <link rel="shortcut icon" href="img/favicon.ico">
    <!-- end: Favicon -->
</head>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container-fluid" style="">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="index.html"> <img alt="Optimus Dashboard" style="width:160px;height:60px" src=@Url.Content("../../img/leviologo.png") /> <span></span></a>

                <!-- start: Header Menu -->
                <div class="btn-group pull-right">
                    <a class="btn" href="~/adminstrator/Mandat/getMandatsNotif">
                        <i class="icon-warning-sign"></i><span class="hidden-phone hidden-tablet"> notifications</span> <span class="label label-important hidden-phone" id="nbmand"></span> 
                    </a>
                    <a class="btn" href="#">
                        <i class="icon-tasks"></i><span class="hidden-phone hidden-tablet"> tasks</span> <span class="label label-warning hidden-phone">17</span>
                    </a>
                    <a class="btn" href="#">
                        <i class="icon-envelope"></i><span class="hidden-phone hidden-tablet"> messages</span> <span class="label label-success hidden-phone">9</span>
                    </a>
                    <a class="btn" href="#">
                        <i class="icon-wrench"></i><span class="hidden-phone hidden-tablet"> settings</span>
                    </a>
                    <!-- start: User Dropdown -->
                    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="icon-user"></i><span class="hidden-phone hidden-tablet"> admin</span>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Profile</a></li>
                        <li class="divider"></li>
                        <li><a href="login.html">Logout</a></li>
                    </ul>
                    <!-- end: User Dropdown -->
                </div>
                <!-- end: Header Menu -->

            </div>
        </div>
    </div>
    <div id="under-header"></div>
    <!-- start: Header -->

    <div class="container-fluid">
        <div class="row-fluid">

            <!-- start: Main Menu -->
            <div class="span2 main-menu-span">
                <div class="nav-collapse sidebar-nav">
                    <ul class="nav nav-tabs nav-stacked main-menu">
                        
                        <li ><a href="index.html"><i class="icon-home"></i><span class="hidden-tablet"> Dashboard</span></a>
                        </li>
                      
                       @* <li>@Html.ActionLink("esm l bouton", "esm l methode", "esmlcontroller", routeValues: null, htmlAttributes: new { id = " id mta3 l bouton " })</li>*@
                       
                        @* <li>@Html.ActionLink("Mandats", "ListeMandat", "Mandat", routeValues: null, htmlAttributes: new { id = "btnMnd" })</li>*@



                        <li><a href="~/adminstrator/Mandat/AddMandat"><i class="icon-edit"></i><span class="hidden-tablet"> Nouveau Mandat</span></a></li>
                        <li><a href="~/adminstrator/Mandat/ListeMandat"><i class="icon-list-alt"></i><span class="hidden-tablet"> Liste Mandat</span></a></li>
                        <li><a href="~/adminstrator/Mandat/Historique"><i class="icon-font"></i><span class="hidden-tablet"> Historique </span></a></li>
                        <li><a href="~/adminstrator/Mandat/Archive"><i class="icon-picture"></i><span class="hidden-tablet"> Archive</span></a></li>
                        <li><a href="table.html"><i class="icon-align-justify"></i><span class="hidden-tablet"> Tables</span></a></li>
                        <li><a href="calendar.html"><i class="icon-calendar"></i><span class="hidden-tablet"> Calendar</span></a></li>
                        <li><a href="grid.html"><i class="icon-th"></i><span class="hidden-tablet"> Grid</span></a></li>
                        <li><a href="file-manager.html"><i class="icon-folder-open"></i><span class="hidden-tablet"> File Manager</span></a></li>
                        <li><a href="icon.html"><i class="icon-star"></i><span class="hidden-tablet"> Icons</span></a></li>
                        <li><a href="login.html"><i class="icon-lock"></i><span class="hidden-tablet"> Login Page</span></a></li>
                    </ul>
                </div><!--/.well -->
            </div><!--/span-->
            <!-- end: Main Menu -->

            <noscript>
                <div class="alert alert-block span10">
                    <h4 class="alert-heading">Warning!</h4>
                    <p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
                </div>
            </noscript>

            <div id="content" class="span10">
                <!-- start: Content -->

                <div>
                    <ul class="breadcrumb">
                        <li>
                            <a href="#">Home</a> <span class="divider">/</span>
                        </li>
                        <li>
                            <a href="#">Dashboard</a>
                        </li>
                    </ul>
                </div>
              
                <div>
                    @RenderBody()
                </div>

                <!-- end: Content -->
            </div><!--/#content.span10-->
        </div><!--/fluid-row-->

        <div class="modal hide fade" id="myModal">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">×</button>
                <h3>Settings</h3>
            </div>
            <div class="modal-body">
                <p>Here settings can be configured...</p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn" data-dismiss="modal">Close</a>
                <a href="#" class="btn btn-primary">Save changes</a>
            </div>
        </div>

        <div class="clearfix"></div>
        <hr>

        <footer>
            <p class="pull-left">&copy; <a href="" target="_blank">creativeLabs</a> 2013</p>
            <p class="pull-right">Powered by: <a href="#">Optimus Dashboard</a></p>
        </footer>

    </div><!--/.fluid-container-->
    <!-- start: JavaScript
    <script src=@Url.Content("../../js/jquery-migrate-1.0.0.min.js")></script>
    <script src=@Url.Content("../../js/jquery-ui-1.10.0.custom.min.js")></script>

    <script src=@Url.Content("../../js/bootstrap.js")></script>

    <script src=@Url.Content("../../js/jquery.cookie.js")></script>

    <script src=@Url.Content("../../js/fullcalendar.min.js")></script>

    <script src=@Url.Content("../../js/jquery.dataTables.min.js")></script>

    <script src=@Url.Content("../../js/excanvas.js")></script>
    <script src=@Url.Content("../../js/jquery.flot.min.js")></script>
    <script src=@Url.Content("../../js/jquery.flot.pie.min.js")></script>
    <script src=@Url.Content("../../js/jquery.flot.stack.js")></script>
    <script src=@Url.Content("../../js/jquery.flot.resize.min.js")></script>

    <script src=@Url.Content("../../js/jquery.chosen.min.js")></script>

    <script src=@Url.Content("../../js/jquery.uniform.min.js")></script>

    <script src=@Url.Content("../../js/jquery.cleditor.min.js")></script>

    <script src=@Url.Content("../../js/jquery.noty.js")></script>

    <script src=@Url.Content("../../js/jquery.elfinder.min.js")></script>

    <script src=@Url.Content("../../js/jquery.raty.min.js")></script>

    <script src=@Url.Content("../../js/jquery.iphone.toggle.js")></script>

    <script src=@Url.Content("../../js/jquery.uploadify-3.1.min.js")></script>

    <script src=@Url.Content("../../js/jquery.gritter.min.js")></script>

    <script src=@Url.Content("../../js/jquery.imagesloaded.js")></script>

    <script src=@Url.Content("../../js/jquery.masonry.min.js")></script>

    <script src=@Url.Content("../../custom.js")></script>

    <script type="text/javascript" language="JavaScript">

	function message_welcome1(){
		var unique_id = $.gritter.add({
			// (string | mandatory) the heading of the notification
			title: 'Welcome on Optimus Dashboard',
			// (string | mandatory) the text inside the notification
			text: 'I hope you like this template',
			// (string | optional) the image to display on the left
			image: '../../img/avatar.jpg',
			// (bool | optional) if you want it to fade out on its own or just sit there
			sticky: false,
			// (int | optional) the time you want it to be alive for before fading out
			time: '',
			// (string | optional) the class name you want to apply to that specific message
			class_name: 'my-sticky-class'
		});
	}

	function message_welcome2(){
		var unique_id = $.gritter.add({
			// (string | mandatory) the heading of the notification
			title: 'Optimus is Amazing Theme',
			// (string | mandatory) the text inside the notification
			text: 'Optimus works on all devices, computers, tablets and smartphones. Optimus has lots of great features. Try It!',
			// (string | optional) the image to display on the left
			image: './../img/avatar.jpg',
			// (bool | optional) if you want it to fade out on its own or just sit there
			sticky: false,
			// (int | optional) the time you want it to be alive for before fading out
			time: '',
			// (string | optional) the class name you want to apply to that specific message
			class_name: 'my-sticky-class'
		});
	}

	function message_welcome3(){
		var unique_id = $.gritter.add({
			// (string | mandatory) the heading of the notification
			title: 'Buy Optimus!',
			// (string | mandatory) the text inside the notification
			text: 'This great template can be yours today.',
			// (string | optional) the image to display on the left
			image: '../../img/avatar.jpg',
			// (bool | optional) if you want it to fade out on its own or just sit there
			sticky: false,
			// (int | optional) the time you want it to be alive for before fading out
			time: '',
			// (string | optional) the class name you want to apply to that specific message
			class_name: 'gritter-light'
		});
	}

	$(document).ready(function(){

		setTimeout("message_welcome1()",5000);
		setTimeout("message_welcome2()",10000);
		setTimeout("message_welcome3()",15000);
		setInterval(f_visits, 100);
		setInterval(f_members, 2000);
		setInterval(f_income, 5000);
		setInterval(f_sales, 5000);
		setInterval(live_notifications_center, 5000);

	});
    </script>
    <!-- end: JavaScript-->


    <!--SignalR  -->
    <script src="~/Scripts/jquery.signalR-2.4.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <script type="text/javascript">
        $(function () {
        // Declare a proxy to reference the hub.
        var chat = $.connection.NotificationHub;
        // Create a function that the hub can call to broadcast messages.
        chat.client.addNewMessageToPage = function (name, message) {


            // Add the message to the page.
            $('#nbmand').text('@Html.Action("Header", "Mandat")');
        };

        $.connection.hub.start().done(function () {
            $('#nbmand').click(function () {
                // Call the Send method on the hub.
                $('#nbmand').text(@Html.Action("Header", "Mandat"));

            });
            $(function() {
                chat.server.send("Alert Mandate", "One mandate have less 40 day to end");

            });

        });
    });
    </script>
 
</body>
</html>